REQUIRE TC_?LIMIT ~mak/lib/THERE/STAT.F

[IFNDEF] BREAK : BREAK  POSTPONE EXIT POSTPONE THEN ; IMMEDIATE  [THEN]

[IFNDEF] ?.NAME
: ?.NAME      ( CFA -- )
\ ELIMINATE " 0x"
\	DUP  H.  \ 1 H.R>S SSPACE
	NEAR_NFA 
	>R DUP
	IF ."  ( " DUP COUNT TYPE 
	     NAME>  R> - DUP
	     IF   DUP ." +" NEGATE H. \ >S
	     THEN DROP        ."  ) "
	ELSE RDROP DROP
	THEN ;
[THEN]

: THERE?_
 IMAGE-BEGIN
 U< 
 ;

VECT THERE?
' THERE?_ TO THERE?

VECT T_C!
VECT T_C@
VECT T_W!
VECT T_W@
VECT T_L!
VECT T_L@
VECT T_! 
VECT T_+!
VECT T_@	
VECT T_2!
VECT T_2@
VECT T_EXECUTE
VECT MAIN_S
\EOF

WARNING @ WARNING 0!
1
[IF]

: C! DUP THERE? IF T_C!	BREAK	C! ;
: C@ DUP THERE? IF T_C@	BREAK	C@ ;
: W! DUP THERE? IF T_W!	BREAK	W! ;
: W@ DUP THERE? IF T_W@	BREAK	W@ ;
: L! DUP THERE? IF T_L!	BREAK	L! ;
: BL! DUP THERE? IF T_L!	BREAK	L! ;
: L@ DUP THERE? IF T_L@	BREAK	L@ ;
:  ! DUP THERE? IF T_! 	BREAK	 ! ;
: +! DUP THERE? IF T_+! BREAK	+! ;
:  @ DUP THERE? IF T_@	BREAK	 @ ; 
: _@ DUP THERE? IF T_@	BREAK	 @ ; 
: 2! DUP THERE? IF T_2! BREAK	2! ;
: 2@ DUP THERE? IF T_2@	BREAK	2@ ; 

: EXECUTE DUP THERE? IF T_EXECUTE BREAK EXECUTE ;
[ELSE]

: QF7_ED
CR ." qF7_ED=<"  HEX .S ." >"
CR R@  ?.NAME
CR RP@ CELL+ @  ?.NAME
CR RP@ CELL+ CELL+ @  ?.NAME
CR RP@ CELL+ CELL+ CELL+ @  ?.NAME

 ;

: C! DUP THERE? IF QF7_ED THEN	C! ;
: C@ DUP THERE? IF QF7_ED THEN	C@ ;
: W! DUP THERE? IF QF7_ED THEN	W! ;
: W@ DUP THERE? IF QF7_ED THEN	W@ ;
: L! DUP THERE? IF QF7_ED THEN	L! ;
: L@ DUP THERE? IF QF7_ED THEN	L@ ;
:  ! DUP THERE? IF QF7_ED THEN	 ! ;
: +! DUP THERE? IF QF7_ED THEN	+! ;
:  @ DUP THERE? IF QF7_ED THEN	 @ ; 
: _@ DUP THERE? IF QF7_ED THEN	 @ ; 
: 2! DUP THERE? IF QF7_ED THEN	2! ;
: 2@ DUP THERE? IF QF7_ED THEN	2@ ; 


: EXECUTE DUP THERE? IF QF7_ED THEN EXECUTE ;
[THEN]
\ : READ-FILE 2>R DUP THERE? IF 2R> TREAD-FILE BREAK 2R> READ-FILE ;

WARNING !

