REQUIRE FILE-EXIST ~mak/lib/ftools.4 

: FLC>
 H-STDOUT >R
 W/O CREATE-FILE THROW  TO H-STDOUT
 ['] INTERPRET CATCH
 H-STDOUT CLOSE-FILE DROP
 R> TO H-STDOUT 
 THROW
 ;
[IFDEF] FILE-EXIST
: FL>
 CR ." FL>=" 
 H-STDOUT >R
 2DUP FILE-EXIST  DUP H.  ." |"
 IF    W/O OPEN-FILE   DUP H.  ." |"
 ELSE  W/O CREATE-FILE
 THEN THROW  TO H-STDOUT
 H-STDOUT  FILE-SIZE  DUP H.  ." |" THROW
 H-STDOUT  REPOSITION-FILE  DUP H.  ." |" THROW

 ['] INTERPRET CATCH
 H-STDOUT CLOSE-FILE DROP
 R> TO H-STDOUT 
 THROW
 ;
[ELSE]
(
: FL>
 H-STDOUT >R
    W/O OPEN-FILE THROW  TO H-STDOUT
 H-STDOUT  FILE-SIZE THROW
 H-STDOUT  REPOSITION-FILE THROW

 ['] INTERPRET CATCH
 H-STDOUT CLOSE-FILE DROP
 R> TO H-STDOUT 
 THROW
 ;
 )

[THEN]

\EOF

S" WORDS.TXT" FL> WORDS

