
: $EFICALL ( <filename> -- )
  R/O OPEN-FILE THROW >R
  R@ FL-SIZE  CR ." FL-SIZE=" DUP H. CR
 DUP ALLOCATE THROW \ size adr
 DUP ROT R@ READ-FILE THROW
  STARTEFI THROW 
  R> CLOSE-FILE DROP
;

: EFICALL PARSE-NAME $EFICALL ;