
 -1 VALUE 'LIT
 -1 VALUE 'IMGLIT
 -1 VALUE 'DATADR
 -1 VALUE 'GET

\ -1 VALUE '(<'>)
\ -1 VALUE 'BRANCH
\ -1 VALUE '?BRANCH
\ -1 VALUE 'EXIT
-1 VALUE '&DBG
-1 VALUE 'NEST
\ -1 VALUE 'UNNEST
\ -1 VALUE 'THCOD
\ -1 VALUE ';EXIT
-1 VALUE 'NOOP
-1 VALUE '(S")
-1 VALUE '(Z")
-1 VALUE 'DUP
-1 VALUE 'DROP
-1 VALUE 'OVER
-1 VALUE '=
-1 VALUE 'ICREATE
-1 VALUE 'TYPE

-1 VALUE 'DEBEXEC
-1 VALUE 'DEB#ADBG
-1 VALUE 'GODEB
-1 VALUE 'GO
-1 VALUE 'MONITOR
-1 VALUE 'R>
-1 VALUE '>R
-1 VALUE VBREAK
-1 VALUE 'P_M>F

-1 VALUE 'QBRANCH

-1 VALUE '(LEAVE)
-1 VALUE 'XDO
-1 VALUE '(DO)
-1 VALUE '(?DO)
-1 VALUE 'ADD[ESP],TOS

\ -1 VALUE 'TOTC
-1 VALUE 'PERFORM
-1 VALUE 'EXECUTE
-1 VALUE 'CATCH
-1 VALUE 'THROW 

0 VALUE 'DOCONSTANT
0 VALUE 'DOVALUE
0 VALUE 'DOVECT
0 VALUE 'DOFIELD
