REQUIRE NUMBER? ~mak/lib/fpcnum.f
REQUIRE API_2: lib\WAPI.4

KERNEL32DLL WAPI2: GetCurrentDirectoryA	GetCurrentDirectoryA

180 CONSTANT DIR_SIZE

CREATE  DIR_STOR  DIR_SIZE ALLOT
CREATE  DIRF_STOR  DIR_SIZE 10 + ALLOT

: DBG_CURFILE,
 CR ." DBG_CURFILE="
  HERE DUP H. TO DBG_CURFILE
 2DUP S",
;


: DBG_INCLUDED
  DBG_CURFILE >R
  YDP_FL >R  1 TO  YDP_FL
  ?YDP><DP   DBG_CURFILE,   ?YDP><DP
  R> TO  YDP_FL
  INCLUDED_
  R> TO DBG_CURFILE
;

' DBG_INCLUDED TO INCLUDED
